### ISSUE TITLE
`IgnoreSourceFiles` should be callable multiple times / allow multiple patterns

### ISSUE THREAD

**Issue by Bios-Marcel** [gtramontina/ooze#14]
Title says it all. Which would be the preferred approach? Personally I'd even opt for both.

I'd potentially make a PR for this.

**Comment by gtramontina** [comment]
Yeah, when I put that together and went on to use it, it immediately felt awkward. Crafting a [single regular expression](https://github.com/gtramontina/ooze/blob/6a8ebab66f3b6fe12d57892d78acde49a9f90e1e/ooze_mutation_test.go#L19) to match multiple and different paths can take quite a lot of trial and error.

That was the first iteration, though. Definitely can be improved. Perhaps starting with allowing multiple patterns, making [`IgnoreSourceFiles`](https://github.com/gtramontina/ooze/blob/6a8ebab66f3b6fe12d57892d78acde49a9f90e1e/options.go#L75) variadic?
