### ISSUE TITLE
Feature request: put test file in a subdirectory

### ISSUE THREAD

**Issue by toejough** [gtramontina/ooze#23]
I'd like to be able to put the test file in a subdirectory.

When I try to put it in `./tests` like all my other test files, though, ooze doesn't find any code to test. 

Happy to try to help, too, if you can point me in the right direction in the code. This is a great tool - thank you for building it!

**Comment by gtramontina** [comment]
Hey @toejough… apologies for the late reply, and thank you for the kind words.

Is your ooze test file under that same `./tests` directory? Have you tried setting the [repository root](https://github.com/gtramontina/ooze?tab=readme-ov-file#settings) to something like `../`?

**Comment by toejough** [comment]
wow, yep, that's all I had to do. repo root `..` and then just adjust the testing line to be `go test -v -tags=mutation ./...` to make `go test` find it alongside the other files. 

I do have to force the colors now to get those to show up, but I'm guessing that's a `go test` thing with output management.

Thanks for the response!
